FROM node:9.11.1-alpine

# Create app directory
WORKDIR /app

ENV MONGO_DB_DEFAULT_PORT 27017
ENV MONGO_DB_DATABASE abDB
ENV MONGO_DB_USER mongodsUser
ENV MONGO_DB_PASSWORD L00pBack
ENV MONGO_DB_NAME abDS
ENV MONGO_DB_TEST_HOST db-test
ENV MONGO_DB_TEST_PORT 27017
ENV MONGO_DB_TEST_URL mongodb://db-test:27017/
ENV API_TEST_PORT 7000

# install mocha for test purpose
RUN npm install mocha@latest -g

# install eslint
RUN npm install eslint@latest -g

# install nsp
RUN npm install nsp@latest -g

# A wildcard is used to copy the package files.
COPY package.json /app/package.json

# Install app dependencies
# For production, use npm install --only=production
RUN npm install
RUN mv /app/node_modules /node_modules

# Bundle app source
COPY . /app

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "test"]


